site_name: "Earthquake Catalog Workshop"
site_url: "https://ai4eps.github.io/Earthquake-Catalog-Workshop"
site_author: ""
site_description: ""
repo_name: "Earthquake Catalog Workshop"
repo_url: "https://github.com/ai4eps/Earthquake-Catalog-Workshop/"

# nav:
#   - Home: 'README.md'
#   - Introduction: 'introduction.md'
#   - Regional Seismic Network: 'seismic_network.md'
#   - Building Earthquake Catalog: 
#     - Machine Learning: 'machine_learning.md'
#     - Template Matching: 'template_matching.md'
#   - Evaluating Earthquake Catalog: 'evaluating_catalog.md'
nav:
    - README: 'README.md'
    - Introduction: 'introduction.md'
    - Regional Seismic Network: 
      - Slides: 'seismic_network.md'
      - Tutorials: 'seismic_network/tutorials.md'
    - Building Earthquake Catalog:
      - Machine Learning: 
        - Slides: 'machine_learning.md'
        - Notebook: 'notebooks/quakeflow.ipynb'
        # - Ridegecrest: 'notebooks/quakeflow_ridgecrest.ipynb'
        # - Hawaii: 'notebooks/quakeflow_hawaii.ipynb'
      - Template Matching:
        - Slides: 'template_matching.md'
        - Notebook1: 'notebooks/tm_one_template.ipynb'
        - Notebook2: 'notebooks/tm_multiple_templates.ipynb'
        - Notebook3: 'notebooks/tm_issues_w_detection_threshold.ipynb'
    - Evaluating Earthquake Catalog: 'catalog_analysis.md'
    - Conclusions: 'conclusion.md'

theme:
  name: "material"
  features:
    - navigation.expand
    - navigation.sections
    # - navigation.tabs
    - navigation.top
    - navigation.tracking

plugins:
  - search
  # - autorefs
  - mkdocs-jupyter:
      ignore_h1_titles: true
      # include_source: true

markdown_extensions:
  - footnotes
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

extra:
  generator: false
  analytics:
    provider: google
    property: G-5P3JS5EJW8

