name: website

on:
  push:
    branches: 
      - master
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material mkdocs-jupyter mkdocs-autorefs mkdocstrings mkdocstrings-python
      - run: |
          mkdir -p docs/introduction && wget -O docs/introduction/SSA25_catalog_workshop_intro.pdf https://github.com/AI4EPS/Earthquake_Catalog_Workshop/releases/download/Slides/SSA25_catalog_workshop_intro.pdf
          mkdir -p docs/seismic_network && wget -O docs/seismic_network/SSA25_catalog_workshop_RSNs.pdf https://github.com/AI4EPS/Earthquake_Catalog_Workshop/releases/download/Slides/SSA25_catalog_workshop_RSNs.pdf
          # wget -O docs/seismic_network/tutorials.md https://raw.githubusercontent.com/SCEDC/tutorials/refs/heads/main/README.md
          mkdir -p docs/machine_learning && wget -O docs/machine_learning/SSA25_catalog_workshop_machine_learning.pdf https://github.com/AI4EPS/Earthquake_Catalog_Workshop/releases/download/Slides/SSA25_catalog_workshop_machine_learning.pdf
          mkdir -p docs/template_matching && wget -O docs/template_matching/SSA25_catalog_workshop_template_matching.pdf https://github.com/AI4EPS/Earthquake_Catalog_Workshop/releases/download/Slides/SSA25_catalog_workshop_template_matching.pdf
          mkdir -p docs/catalog_analysis && wget -O docs/catalog_analysis/SSA25_catalog_workshop_quality.pdf https://github.com/AI4EPS/Earthquake_Catalog_Workshop/releases/download/Slides/SSA25_catalog_workshop_quality.pdf
          mkdir -p docs/conclusion && wget -O docs/conclusion/SSA25_catalog_workshop_conclusion.pdf https://github.com/AI4EPS/Earthquake_Catalog_Workshop/releases/download/Slides/SSA25_catalog_workshop_conclusion.pdf

      - run: wget -O docs/template_matching/animated_template_matching.mp4 https://github.com/AI4EPS/Earthquake_Catalog_Workshop/releases/download/Slides/animated_template_matching.mp4
      - run: mkdocs gh-deploy --force
