name: website

on:
  push:
    branches: 
      - master
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material mkdocs-jupyter mkdocs-autorefs mkdocstrings mkdocstrings-python
      - run: curl -o machine_learning/SSA25_catalog_workshop_machine_learning.pdf https://github.com/AI4EPS/Earthquake_Catalog_Workshop/releases/download/Slides/SSA25_catalog_workshop_machine_learning.pdf
      - run: mkdocs gh-deploy --force
